# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

if [ ! -d "$HOME/.zsh" ]; then
  git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git $HOME/.zsh/zsh-snap
fi
source $HOME/.zsh/zsh-snap/znap.zsh

znap source Tarrasch/zsh-autoenv 

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

znap source romkatv/powerlevel10k
znap source jeffreytse/zsh-vi-mode
function zvm_after_init() {
znap source zsh-users/zsh-autosuggestions  # On same line
  export ZSH_AUTO_SUGGEST_USE_ASYNC=true
znap eval junegunn/fzf 'command -v fzf >/dev/null 2>&1 || {./install --bin} >/dev/null'
  znap source junegunn/fzf shell/{completion,key-bindings}.zsh
  path=(~[junegunn/fzf]/bin $path .)

znap source marlonrichert/zsh-autocomplete
  zstyle ':autocomplete:*' min-input 1
  zstyle ':autocomplete:tab:*' insert-unambiguous no
  zstyle ':autocomplete:tab:*' widget-style menu-select
  zstyle ':autocomplete:tab:*' fzf yes

}
znap source wfxr/forgit
znap source zpm-zsh/colors
znap source zpm-zsh/ls
znap source hlissner/zsh-autopair
znap source MichaelAquilina/zsh-you-should-use
znap source zdharma/fast-syntax-highlighting
znap source zsh-users/zsh-completions
znap source agkozak/zsh-z

znap eval trapd00r/LS_COLORS '{ command -v gdircolors >/dev/null 2>&1 } && { gdircolors -b LS_COLORS} || { dircolors -b LS_COLORS}'
  zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
znap eval fuck 'thefuck --alias'
znap eval pip 'python3 -m pip completion --zsh'
znap eval brew-shellenv '{ command -v brew >/dev/null 2>&1 } && { brew shellenv }'
znap eval kitty 'kitty + complete setup zsh'

source ~/.config/lf/lficons.rc

EDITOR="nvim"
command -v floaterm >/dev/null 2>&1 && EDITOR="floaterm"
alias v="$EDITOR" vimdiff="nvim -d"

alias g="git" lg="EDITOR=nvim lazygit"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse"

export PAGER="bat"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
