if [ ! -d "$HOME/.zsh" ]; then
  git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git $HOME/.zsh/zsh-snap
fi
source $HOME/.zsh/zsh-snap/znap.zsh

znap source romkatv/powerlevel10k
# znap source jeffreytse/zsh-vi-mode
# function zvm_after_init() {
znap source junegunn/fzf shell/{completion,key-bindings}.zsh
  export FZF_DEFAULT_OPTS="--layout=reverse"
  # export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
  export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
# }

znap install Homebrew/brew
znap source marlonrichert/zsh-autocomplete
  zstyle ':autocomplete:*' min-input 0
  zstyle ':autocomplete:*' insert-unambiguous yes
  zstyle ':autocomplete:*' widget-style menu-select
  zstyle ':autocomplete:*' fzf-completion yes
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
znap source zsh-users/zsh-autosuggestions  # On same line
znap source zpm-zsh/colors
znap source zpm-zsh/ls # Use exa for ls
znap source zpm-zsh/autoenv
znap source hlissner/zsh-autopair
znap source MichaelAquilina/zsh-you-should-use
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-completions
znap source ajeetdsouza/zoxide
znap source wez/wezterm assets/shell-integration/wezterm.sh

znap eval pip 'python3 -m pip completion --zsh'
znap eval kitty 'kitty + complete setup zsh'
[[ "$TERM" == "xterm-kitty" ]] && alias ssh="kitty +kitten ssh"
znap eval fuck 'thefuck --alias'
znap install esc/conda-zsh-completion
znap install ogham/exa
znap fpath _poetry 'poetry completions zsh'

export EDITOR="nvim"
if [[ -v NVIM_LISTEN_ADDRESS ]]; then EDITOR="nvr" fi
command -v floaterm >/dev/null 2>&1 && EDITOR="floaterm"
alias v="$EDITOR" vimdiff="nvim -d"
alias g="git" lg="lazygit"

export PAGER="bat"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export SAVEHIST=2000
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=2000

source $HOME/.config/lf/lficons.rc
[ -n "$WEZTERM_PANE" ] && export NVIM_LISTEN_ADDRESS="/tmp/nvim$WEZTERM_PANE"

autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line
