if [ ! -d "$HOME/.zsh" ]; then
  git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git $HOME/.zsh/zsh-snap
fi
source $HOME/.zsh/zsh-snap/znap.zsh

znap source romkatv/powerlevel10k
znap source jeffreytse/zsh-vi-mode
function zvm_after_init() {
znap source zsh-users/zsh-autosuggestions  # On same line
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
znap source junegunn/fzf shell/{completion,key-bindings}.zsh
  export FZF_DEFAULT_OPTS="--layout=reverse"
  # export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
  export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
znap source marlonrichert/zsh-autocomplete
  zstyle ':autocomplete:*' min-input 1
  zstyle ':autocomplete:*' widget-style menu-select
  zstyle ':autocomplete:*' fzf-completion yes
}
znap source zpm-zsh/colors
znap source zpm-zsh/ls # Use exa for ls
znap source zpm-zsh/autoenv
znap source hlissner/zsh-autopair
znap source MichaelAquilina/zsh-you-should-use
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-completions
znap source ajeetdsouza/zoxide

znap eval pip 'python3 -m pip completion --zsh'
znap eval kitty 'kitty + complete setup zsh'
znap eval fuck 'thefuck --alias'
znap install esc/conda-zsh-completion
znap install ogham/exa
znap install Homebrew/brew
znap fpath _poetry 'poetry completions zsh'

export EDITOR="nvim"
if [[ lvim ]]; then EDITOR="lvim" fi
if [[ -v NVIM_LISTEN_ADDRESS ]]; then EDITOR="nvr" fi
command -v floaterm >/dev/null 2>&1 && EDITOR="floaterm"
alias v="$EDITOR" vimdiff="nvim -d"
alias g="git" lg="lazygit"

export PAGER="bat"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

source $HOME/.config/lf/lficons.rc
